global using Ardalis.GuardClauses;
global using AutoMapper;
global using AutoMapper.QueryableExtensions;
global using Microsoft.EntityFrameworkCore;
global using FluentValidation;
global using MediatR;
global using MonitorGlass.Application.Common.Models;
global using MonitorGlass.Application.Common.Interfaces;
global using MonitorGlass.Application.Common.Mappings;